services:
  puzzle:
    image: ghcr.io/repute-software/repute-puzzle:latest
    container_name: sliding-puzzle
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images:ro
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    environment:
      - TZ=UTC
      - RESEND_API_KEY=${RESEND_API_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

